[[template]]
src = "alire.toml.in"
dst = "alire.toml"

[[template]]
src = "ravenscar_build.gpr.in"
dst = "ravenscar_build.gpr"
excluded_profiles = ["light"]

[[template]]
src = "runtime_build.gpr.in"
dst = "runtime_build.gpr"

[[template]]
src = "rp2040_runtime_config.ads.in"
dst = "gnat_user/rp2040_runtime_config.ads"

[[template]]
src = "rp2040_runtime_config.h.in"
dst = "gnat_user/rp2040_runtime_config.h"