on:
    push:
      branches:
        - main
    pull_request:
    workflow_dispatch:

jobs:

  build-and-test:
    strategy:
      matrix:
        # Also build on Windows since there have been some windows-specific
        # problems in the past around line ending style checks.
        os: ["ubuntu-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - uses: alire-project/setup-alire@v6
        with:
          version: 2.1.1
          toolchain: 'gnat_arm_elf gprbuild'

      - name: Generate Runtimes
        shell: bash
        run: ./generate-runtimes.sh

      - name: Build Runtimes
        shell: bash
        run: |
          for dir in install/*/; do
            echo "::group::Build $(basename $dir)"
            (cd $dir && alr build --validation)
            echo "::endgroup::"
          done

      - name: Install Test Dependencies
        run: |
          pip install -r tests/requirements.txt

      - name: Run tests
        run: |
          cd tests
          pytest . -v --junit-xml=reports/runtime-tests.xml

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: Runtime Tests
          path: tests/reports/*.xml
          reporter: java-junit
